# Supabase credentials
supabase_url = "https://your-project-id.supabase.co"
supabase_key = "your-supabase-anon-key"

# API keys
alpha_vantage_api_key = "YOUR_ALPHA_VANTAGE_KEY"
finnhub_api_key = "YOUR_FINNHUB_KEY_HERE"  # Optional