# Supabase credentials
supabase_url = "https://tehrcjfulqxsoabjpfrx.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlaHJjamZ1bHF4c29hYmpwZnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzIxOTQsImV4cCI6MjA2MjU0ODE5NH0._xd5ipaNxKko9tZsjBC6sQruubQEPQCBUYXERWPHqmg"

# API keys
# You need to get a free API key from https://www.alphavantage.co/support/#api-key
alpha_vantage_api_key = "5LU2EKREIF85DZTC"

# Optional API keys
# finnhub_api_key = "YOUR_FINNHUB_KEY_HERE"  # Optional